# Generated by Django 5.1.5 on 2025-01-18 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_subsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingquestion',
            name='has_options',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Home.bookingquestion')),
            ],
        ),
    ]
