# Generated by Django 5.1.5 on 2025-01-18 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_bookingquestion_has_options_questionoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingquestion',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Home.subcategory'),
        ),
    ]
