# Generated by Django 5.1.5 on 2025-01-23 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_customer_address_customer_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='address',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='longitude',
        ),
    ]
