# Generated by Django 5.1.5 on 2025-01-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_serviceprovider_name_alter_appointment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='pincode',
            field=models.CharField(blank=True, default='0000', max_length=10, null=True),
        ),
    ]
