# Generated by Django 5.1.5 on 2025-02-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_customer_address_customer_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
