# Generated by Django 5.1.5 on 2025-02-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_appointmentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('Payment Pending', 'Payment Pending'), ('Paid', 'Paid')], default='Payment Pending', max_length=20),
        ),
    ]
