# Generated by Django 5.1.5 on 2025-02-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_appointment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='extra_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
