# Generated by Django 5.1.5 on 2025-02-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_appointment_extra_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('Payment Pending', 'Payment Pending'), ('Extra', 'Extra'), ('Paid', 'Paid')], default='Payment Pending', max_length=20),
        ),
    ]
