# Generated by Django 5.1.5 on 2025-02-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
