# Generated by Django 5.1.5 on 2025-03-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_appointment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
